### ISSUE TITLE
Write documentation for PyLink's core

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#113]
TBD in `docs/technical/`:
- [x] Protocol specification (`pmodule-spec.md`)
- [x] ~~Using PyLink's utils module (`using-utils.md`)~~ <br>Auto-generated docs from PyDoc are a lot better than anything I can come up with :)
- [x] PyLink hooks reference (`hooks-reference.md`)
- [x] Document `classes.py`
- [ ] Mention the special `main()` and `die()` functions a plugin can use to listen for plugin (un)loading.
- [x] ~~Writing tests for PyLink modules (`writing-tests.md`)~~ Maybe not for 1.0

**Comment by GLolol** [comment]
Also:

- [ ] Mention the special `main()` and `die()` functions a plugin can use to trigger plugin removals/creations.
