### ISSUE TITLE
Clientbot support - connecting PyLink as a bot on remote servers

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#144]
Work is done in the `devel` branch (branched off 0.9-beta1). Planning credits go to @Techman- and @cooper as well :)

#### Goals
- Expose PyLink's framework and various plugins to people on any regular network using a bot.
- `protocols/clientbot.py` should support as much of (a subset of) IRC S2S as reasonably possible. 
- Aim for the *least* amount of Clientbot-specific code in most plugins.

#### Checklist for now (26/07/2016)
- [x] Make dummy UID/SID generators based on a counters, similarly to what's done to support UnrealIRCd 3.2.
- [x] Grab casemapping token from 005 / RPL_ISUPPORT
- Generic protocol module specification. All messages will have to be routed through the PyLink clientbot regardless of the `sender` argument, because there's only one BOT to send from.
    - [x] **`connect`**`(self)`
    - [x] **`handle_events`**`(self, line)`
    - [x] **`ping`**`(self, source=None, target=None)`
    - [x] **`spawnClient`**`(self, nick, ident='null', host='null', realhost=None, modes=set(), server=None, ip='0.0.0.0', realname=None, ts=None, opertype=None, manipulatable=False)` *half-STUB*
    - [x] **`join`**`(self, client, channel)`
        - [x] inbound
    - [x] **`away`**`(self, source, text)` **STUB**
        - [ ] inbound
    - [x] **`invite`**`(self, source, target, channel)`
    - [x] **`kick`**`(self, source, channel, target, reason=None)`
        - [x] inbound
        - [x] Check for failed KICK attempts. Currently the target becomes a ghost if the kick relayed through Clientbot fails.
    - [x] **`kill`**`(self, source, target, reason)` **STUB**
    - [ ] **`knock`**`(self, source, target, text)`
    - [x] **`message`**`(self, source, target, text)` - *How should messages be formatted? Can they be all pretty like IRC bot relayers, or should this be up to plugins?*
        - [x] inbound
    - [ ] **`mode`**`(self, source, target, modes, ts=None)` - #287 
        - [x] inbound
    - [x] **`nick`**`(self, source, newnick)` *half-STUB*
        - [x] inbound
    - [x] **`notice`**`(self, source, target, text)`
    - [x] **`numeric`**`(self, source, numeric, target, text)` **STUB**
    - [x] **`part`**`(self, client, channel, reason=None)` *half-STUB*
        - [x] inbound
    - [x] **`quit`**`(self, source, reason)` *half-STUB*
        - [x] inbound
    - [x] **`sjoin`**`(self, server, channel, users, ts=None)` **STUB**
    - [x] **`spawnServer`**`(self, name, sid=None, uplink=None, desc=None)` **STUB**
    - [x] **`squit`**`(self, source, target, text='No reason given')` **STUB**
    - [ ] **`topic`**`(self, source, target, text)` - *has to check for op first* - #291
        - [ ] inbound
    - [ ] **`topicBurst`**`(self, source, target, text)` **STUB**
    - [x] **`updateClient`**`(self, source, field, text)` **STUB**
- [x] Fill in `self.cmodes` / `self.umodes` / `self.prefixmodes`
- [x] Handle NAMES first to enumerate user lists.
    - The difference between NAMES and WHO? The latter is more verbose, but the former sends more individual user data at once.
    - [x] Implement periodic WHO polling (this is needed **only if** `userhost-in-names` isn't supported, but we may as well implement the fallback first):
        - [x] ~~Make a queue of users that we lack /WHO data for as we parse /names.~~ not needed
        - [x] Store WHO lines (352/RPL_WHOREPLY) as they arrive, but *only* burst join users and remove them from the queue when 315/RPL_ENDOFWHO is received.
```
00:22 <@GL> question: if i'm handling WHO w/o userhost-in-names do i even need to care about NAMES output?
00:24 <%mad/nt> most things rely on both.. use NAMES to update the userlist and WHO just for user information..
00:24 <+Techman> /who has all the info that /names does
00:24 <+Techman> It's just that only /names is sent on channel join
00:26 <%mad/nt> still, not handling NAMES would be bad
00:27 <+Techman> You can use it to get initial user info
00:27 <+Techman> That's about it
00:29 <%mad/nt> you can process joins and status modes several at a time instead of individually
00:29 <%mad/nt> which is important for a relay because it would be spammy if you relied only on WHO
00:33 <%mad/nt> anyway the point is that the purpose of WHO is not to track channel membership; it is for obtaining other information associated with users
```
- [x] When the clientbot is KICKed from a channel, it should clear all channel data and fake KICKs for relay, etc.
    - [x] Ditto when the bot is forced to leave a channel.
- [ ] Loosen configuration validation for clientbot, as things like `recv/sendpass`, `sid`, etc. aren't needed (#282)
- [x] Track oper in `/names`
- [ ] Track deoper in `/names` - #289 
- [ ] keepnick for netsplits, ping timeouts, etc. - #288

#### Other good features
For the future, in order of likely usefulness:
- [x] NickServ login / Autoperform config option
- IRCv3 caps and similar - #290
    - [ ] Basic negotiation
    - [ ] `multi-prefix`
        - [ ] Fall back to `PROTOCL NAMESX` when available in RPL_ISUPPORT
    - [ ] `account-notify` and `extended-join` for services account tracking
    - [ ] `userhost-in-names` - eliminates the need for periodic WHO polling
        - [ ] Fall back to `PROTOCL UHNAMES` when available in RPL_ISUPPORT
    - [ ] `away-notify` - updates AWAY status without WHO polling
    - [ ] SASL login
- [ ] Built-in flood protection - #293
- [ ] PM/notice routing for relay? - #292
- [ ] Relay modes (op, etc.) across clientbot? This would only work if the bot is opped, and the modes it tries to set are available (e.g. not oper only). Special checks would have to be done but this isn't necessarily reliable. - #287

**Comment by GLolol** [comment]
The goal is to integrate this with #99 so that instead of PyLink doing connections directly via client-to-server code, *existing bot frameworks* (supybot, eggdrop, etc.) can be used to go into channels and forward what it sees to PyLink daemon(s) via a S2S protocol. But I'm still thinking about how to structure such a protocol to be extensible and efficient.

**Comment by GLolol** [comment]
Save for #282 and #289, the bulk of clientbot supported is working. The rest have been split into separate issues.
