### ISSUE TITLE
Standardize lists of all the named modes PyLink recognizes

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#200]
This would probably go into `docs/technical/`.

edit: 200th issue! :fireworks:

- [x] Channel modes list
- [ ] User modes list
- [x] Mention these lists in `pmodule-spec.md` or whatever

**Comment by DanielOaks** [comment]
Whoo, would certainly be helpful. Possibly also note the value (if any) that goes along with them, so people can more easily confirm modes mean the same thing between different protos.

**Comment by GLolol** [comment]
Yeah, that's the intention. A best format would probably be a table listing the modes, and whether they're supported by each IRCd, and which mode character if so.
