### ISSUE TITLE
[help wanted] 0.9.x docs meta-issue

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#224]
- [x] Tutorial for automode
- [x] Mention exttarget usage (straight out of the docstrings most likely)
- [ ] technical: document the new service bot API
- [ ] Redo autogenerated docs to use the setuptools-installed version (how?!)
