### ISSUE TITLE
Docs meta issue for 0.10.x

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#284]
- [x] Clientbot: mention which server options it needs and doesn't need compared to other protocol modules (#282)
- [x] Mention relay_clientbot (the plugin)
- [x] Permissions system (waiting for #190)
- [x] Make a list of all permissions used by PyLink plugins.
- [ ] ~~Mention clientbot_styles config options.~~ Postponed; issue split into #335
- [x] Mention protocol specific conf key validation (#282)
