### ISSUE TITLE
Create PyLink PPA for Ubuntu packages

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#357]
- Dependencies:
  - [x] ircmatch (autobuild for trusty, xenial, yakkety, zesty)
  - [x] ~~pypandoc (backport needed for trusty, xenial)~~
  - [ ] expiringdict (backport needed for trusty)
- [ ] pylink (autobuild for trusty, xenial, yakkety, zesty)

**Comment by GLolol** [comment]
This has been done: see https://launchpad.net/~tacocat/+archive/ubuntu/pylink
