### ISSUE TITLE
[discuss] PyLink Relay plugin

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#37]
The objective: a PyLink-Relay plugin would be a replacement / alternative for Janus. Related issues: #23 #39 #40.

TODO:
- [x] Write some sort of database implementation for storing channel links.
    - [x] Write a scheduler so we can save the database periodically. #41.
- [x] `CREATE` command (simply `CREATE #channel` on any net)
- [x] `DESTROY/REMOVE` command for removing a channel
- [x] `LINK` command
    - Figure out the best syntax for this: What flows the best and is the least ambiguous? Remember that the name used by a remote channel doesn't the local one (i.e. a channel can have `#name1` on one net, and `#name2` on another).
        -  ~~`LINK remotenet#chan #local-chan-name`~~
        - `LINK remotenet #chan #local-chan-name`
        - ~~`LINK remotenet #chan TO #local-chan-name` ("TO" would be a case-insensitive, required keyword)~~
- [x] `DELINK` command:
     - When ran on the network owning a channel, you can delink any remote network if they're being a problem: `DELINK #ourchan remotenet`
    - Otherwise, any network can remove a link to a remote channel via `DELINK #somechan`.
- [x] Work out all the handler stuff (relaying events).
    - [x] ~~Spawn a pseudoserver for every linked network, squitting them when they disconnect.~~ Too much work, not enough gain.
    - [x] Mode changes need to be filtered so that only modes that exist on the remote net are sent. Also, mode chars need to be mapped for different networks (e.g. `+R` on InspIRCd/UnrealIRCd corresponds to `+r` on charybdis-based nets).
    - [ ] Filter out banlists so that invalid bans aren't sent to remote nets: i.e. extbans. Something like `R:baduser` on InspIRCd wouldn't be valid elsewhere. #55.
        - This is especially bad because Unreal will convert this into `R:baduser!*@*` automatically, which can cause messy desyncs!
    - [x] A nettag suffix of `/net` would need to be coersed to `|net` to prevent protocol violations on charybdis. (Replace `/` with `|` globally)
    - [ ] Nick collisions need to be handled properly, but how? We should tag our users, but what if a tagged nick like `person|net` becomes taken on a remote network too? Here are some options (**discuss**): #61
        - On nick collision, increase the septag length by one: `person|net` -> `0ALAAAAAA` -> `person||net`
        - ~~Same, but also put a number in? Janus does this currently. `person|net` -> `0ALAAAAAA` -> `person|1|net`~~
        - ~~Be more aggressive and send a kill/SAVE to the remote net to gain our nick back. This has its own consequences, so I'm not convinced it's the best idea. On UnrealIRCd 3.2, a kill would be necessary because a SAVE-like command doesn't exist (UIDs are only starting to be used in Unreal 3.4-alpha)~~
        - ~~Append an underscore (thanks @jameswritescode for contributing): `person|net` -> `person_|net` -> `person__|net` ...~~
    - [x] Also, nicks need to be checked to make sure they don't cause protocol violations by going over the max nick length or starting with a number.
        - Cut off nicks that go over the nick length, but NOT the separating tag. `ObnoxiouslyLongNick/testnet` would turn into `ObnoxiouslyL/testnet` on a net with 20 max nick length, for example.
        - Nicks starting with a UID should be prefixed with a `_`.
    - [x] Should we force tags on remote users? i.e. GLolol would be GLolol/othernet all the time. There are two arguments to this (**discuss**):
        - **Yes** - Prevents nick collisions as long as we're allowed to use `/` in nicks (InspIRCd/UnrealIRCd 3.2.x)
        - **No** - Makes nicks too long / ugly
    - [x] Drop kills destined to remote users entirely. This is different from Janus, which kicks the user on every shared channel, because there's no real benefit of causing kick floods like this in the first place. The killer should get a stern message from the PyLink client that this would be ineffective. #47. 5999eedd984d3b28d24b1a2f1337af1f868df679
    - [x] Quit clients that leave all shared channels, to prevent inflation of `/LUSERS` cf32461d8ec1a2172a05a8bd00e72f6c86293884

### Features for later

- [ ] `CLAIM` command for maintaining channel ownership. #51
    - Networks that create a channel automatically get ownership over it. This means override (unopped) kicks and kills will be blocked. The `CLAIM` command can then be used to add other trusted networks where override is allowed.
   - [ ] Maybe if you have are added to a channel's `CLAIM`, you should get control over `DELINK`'ing others too.
- Do we need a `BAN` command for Relay users? Janus' BAN command is regex based and seriously broken in most cases... Allowing bans to be set on remote users/IPs in the form of G/K/ZLines should be opt-in, not implicitly allowed. Worst case scenario: delink the nets with problematic users.
- [ ] Only allow messaging remote users that share a channel with you. #62

Very important final note: don't cause unnecessary netsplits and desyncs for our networks. :)

**Comment by gbyers** [comment]
Top Kek

**Comment by rnjohnson18** [comment]
On the LINK command, I think option 2 would be the best choice as it's more consistent with the rest of IRC command and is easy to understand.
As to the topic of nick collisions, increasing the separator is my pick as it doesn't increase the length of the nick by much, yet it's still noticeable for most people to tell that their nick collided. I also agree that nick tagging should be enforced by DEFAULT, and the option could be changed within the config. Nick tagging makes it easier to identify what network a user is chatting from, and convenience is more important than aesthetics I'd say. The nicks with tags doesn't have to be long, you can enforce all the remote nicknames to be 20 chars or less, for example, and that would squash the length issue and maximum nickname limit issue.
YES, there needs to be a method of banning remote users somehow... not all networks will follow through with user's requests at delinking troublesome nets or will take the steps to prevent them. How to implement a working ban command I'd have no clue...

-Ryan

**Comment by siniStar7boy** [comment]
I'm in agreement with almost every idea.

As far as **claim**, I don't know that I would agree it should be on by default.  Staff abuse from other networks should result in disciplinary action or delink of that link.  _(But being on by default could also hinder helping networks/channels where their staff are idle/away during a floodbot attack or similar.)_

I agree with @rnjohnson18 in almost all of his cases. _(Especially if nicknames could be enforced at a certain char count)_

I do agree the ban function in Janus is currently _(almost)_ useless.  It would be nice if there was an ability to send G/K/Z:lines through to linked networks.  _To avoid drama, it should as already mentioned above, probably be opt-in._

**Comment by GLolol** [comment]
As far as I'm concerned, we can't enforce nick length on networks as a PseudoServer, because that's almost always set by the IRCd. The de facto max nick length would be the network's allowed nick length minus the length of the tag separator (if it is turned on).

**Comment by GLolol** [comment]
Well, the basics for PyLink-Relay are just about finished! :open_mouth:

Anything that hasn't been added yet has been split into their own issues. Closing accordingly!
