### ISSUE TITLE
Break up Irc() into a state tracker and a socket-based subclass

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#371]
This would allow PyLink to establish virtual connections to non-IRC services (e.g. XMPP, Telegram)

- [x] Break up `connect()`, connect loop threading, `disconnect()`, `run()`, and `send()` into an IRC specific class
    - Depending on the framework we're hooking into, 3rd-party transports may choose to skip `run()` and `send()` entirely.
    - [xmpppy](http://xmpppy.sourceforge.net/) has its own `registerHandler()`, for example
- [x] ~~Call protocol specific disconnect code `irc.proto.disconnect()` if defined~~ Split protocol specific and protocol agnostic connect/disconnect code
- [x] Move `schedulePing()` into this new (IRC-specific) class, and possibly allow turning ping checks off entirely
