### ISSUE TITLE
[2.0] Update protocol spec documentation

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#478]
Some of the things that need to be mentioned:

- [x] The old `Irc` and `Protocol` classes were merged together in 2.0, meaning that there is now only one `connect()` function in each class
    - [x] IRCd protocol modules that used to define `connect()` now define `post_connect()` to prevent a name collision (this is an API breaking change!)
- [x] 2.0 protocol modules should now inherit from either classes.IRCNetwork, classes.PyLinkNetworkCoreWithUtils, or protocols.ircs2s_common.IRCCommonProtocol based on how much separation is needed
    - XXX: elaborate more on this
- [x] Renamed members:
    - [x] spawnClient → spawn_client
    - [x] spawnServer → spawn_server
    - [x] updateClient → update_client
    - [x] topicBurst → topic_burst
    - [x] connect → post_connect
    - [x] ping → _ping_uplink (also updated args)
- [x] Mention specific lists that need to be enumerated
    - [x] On connect, add the user to its servers' user list; this is needed for SQUIT handling
    - [x] On JOIN, add the user to the channels' user list AND the channel to the users' channel list - plugins implicitly depend on this consistency in various places
