### ISSUE TITLE
Finish off extban support

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#498]
- [x] Acting extbans (e.g. quiet)
    - [x] quiet ffde2c6b32edb9d100ee9b5af7111f8ccb000293
    - [x] nonick 3c675bb163d1382f54b534bd9d6da31d63a7f2cc
    - [x] the rest
- [x] Matching extbans (e.g. ban users matching a certain account)
- [x] Add a supported extbans table, using the same format as `channel/user-modes.csv`
