### ISSUE TITLE
Revise docs/advanced-relay-config.md

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#597]
- [x] Use `::` instead of `:` to separate blocks for consistency with the example-conf
- [ ] Explicitly document (with defaults) the events that relay_clientbot supports
- [ ] Make it super clear how to disable colors using relay_clientbot using overridden styles
